server:
  port: 9082
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=GMT%2B8
    username: root
    password: 123456
#security:
#  user:
#    name: tom
#    password: 123
#    roles:
#      - USER
logging:
  level:
    com.tom.dao: debug
#配置 client配置注册中心地址，instance-id定义在注册中心的实例名称
#prefer-ip-address当鼠标点击查看的时候应该以IP作为链接项
eureka:
  client: #向服务端注册
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:enjoy@eureka3:7003/eureka
    ##fetch-registry: true
  instance:
    instance-id: userconfig
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    #lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
    hostname: userconfig

#springboot的actuate监控配置
info:
  app.name: userconfig
  company.name: tom
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
