server:
  port: 8001
  
  
eureka:
  instance:
    instance-id: consumer-user
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka