server:
  port: 8000


eureka:
  instance:
    instance-id: cloud-user1
    prefer-ip-address: true
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka