spring:
  profiles:
    active:
      - dev


server:
  port: 7001
#eureka配置
#定义eureka实例，hostname为eureka所在的主机名称
eureka:
  instance:
    hostname: localhost
#eviction-interval-timer-in-ms设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  server:
    #eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    fetch-registry: false #eureka本身也是一个服务，服务端不需要去获取注册的服务信息
    register-with-eureka: false #服务端不需要注册

spring:
  profiles: dev
  security:
    user:
      name: admin
      password: enjoy
---  
server:
  port: 7002
#eureka配置
#定义eureka实例，hostname为eureka所在的主机名称
eureka:
  instance:
    hostname: localhost
#eviction-interval-timer-in-ms设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  server:
    #eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    fetch-registry: false #eureka本身也是一个服务，服务端不需要去获取注册的服务信息
    register-with-eureka: false #服务端不需要注册

spring:
  profiles: beta
  security:
    user:
      name: admin
      password: enjoy
